CREATE TABLE users (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR(64) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	username VARCHAR(64) UNIQUE NOT NULL,
	xp INT DEFAULT 0
);
